
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
   
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 835)
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        
        ######################## Buttons Original ############
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.startbutton1 = QtWidgets.QPushButton(self.centralwidget)
        self.startbutton1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("brush.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startbutton1.setIconSize(QtCore.QSize(40, 40))
        self.startbutton1.setIcon(icon)
        self.startbutton1.setObjectName("startbutton1")
        self.horizontalLayout.addWidget(self.startbutton1)
        
        self.pausebutton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pausebutton1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pausebutton1.setIcon(icon1)
        self.pausebutton1.setIconSize(QtCore.QSize(40, 40))
        self.pausebutton1.setObjectName("pausebutton1")
        self.horizontalLayout.addWidget(self.pausebutton1)


        self.startsong_orig = QtWidgets.QPushButton(self.centralwidget)
        self.startsong_orig.setTabletTracking(False)
        self.startsong_orig.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("sound.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startsong_orig.setIcon(icon2)
        self.startsong_orig.setIconSize(QtCore.QSize(40, 40))
        self.startsong_orig.setObjectName("uploadfilebutton1")
        self.horizontalLayout.addWidget(self.startsong_orig)

        self.stopm_orig = QtWidgets.QPushButton(self.centralwidget)
        self.stopm_orig.setTabletTracking(False)
        self.stopm_orig.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopm_orig.setIcon(icon2)
        self.stopm_orig.setIconSize(QtCore.QSize(40, 40))
        self.stopm_orig.setObjectName("uploadfilebutton1")
        self.horizontalLayout.addWidget(self.stopm_orig)

################################ Fourier orig #############################################

        spacerItem = QtWidgets.QSpacerItem(1050, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.startbuttonFForig = QtWidgets.QPushButton(self.centralwidget)
        self.startbuttonFForig.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Fourier2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startbuttonFForig.setIcon(icon3)
        self.startbuttonFForig.setIconSize(QtCore.QSize(40, 40))
        self.startbuttonFForig.setObjectName("startbuttonFForig")

        self.horizontalLayout.addWidget(self.startbuttonFForig)
        
        self.stopbuttonFForig = QtWidgets.QPushButton(self.centralwidget)
        self.stopbuttonFForig.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopbuttonFForig.setIcon(icon4)
        self.stopbuttonFForig.setIconSize(QtCore.QSize(40, 40))
        self.stopbuttonFForig.setObjectName("stopbuttonFForig")
        self.horizontalLayout.addWidget(self.stopbuttonFForig)
        
        
        
        spacerItem1 = QtWidgets.QSpacerItem(288, 38, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.max = QtWidgets.QPushButton(self.centralwidget)
        self.max.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("max.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max.setIcon(icon5)
        self.max.setIconSize(QtCore.QSize(40, 40))
        self.max.setObjectName("max")
        self.horizontalLayout.addWidget(self.max)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        #######################  plot original #############

        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.orgwin = PlotWidget(self.centralwidget)
        self.orgwin.setObjectName("orgwin")
        self.gridLayout.addWidget(self.orgwin, 0, 0, 1, 1)
        
        self.fourer_org_win = PlotWidget(self.centralwidget)
        self.fourer_org_win.setObjectName("fourer_org_win")
        self.gridLayout.addWidget(self.fourer_org_win, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)

        ########################## Equliazer orig ##############
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        
        self.startbuttonEq = QtWidgets.QPushButton(self.centralwidget)
        self.startbuttonEq.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("draeEq.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startbuttonEq.setIcon(icon6)
        self.startbuttonEq.setIconSize(QtCore.QSize(40, 40))
        self.startbuttonEq.setObjectName("startbuttonEq")
        self.horizontalLayout_6.addWidget(self.startbuttonEq)
        
        self.pausebuttonEq = QtWidgets.QPushButton(self.centralwidget)
        self.pausebuttonEq.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("eraser.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pausebuttonEq.setIcon(icon7)
        self.pausebuttonEq.setIconSize(QtCore.QSize(40, 40))
        self.pausebuttonEq.setObjectName("pausebuttonEq")
        self.horizontalLayout_6.addWidget(self.pausebuttonEq)
        
        self.startsong_Eq = QtWidgets.QPushButton(self.centralwidget)
        self.startsong_Eq.setTabletTracking(False)
        self.startsong_orig.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("sound.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startsong_Eq.setIcon(icon8)
        self.startsong_Eq.setIconSize(QtCore.QSize(40, 40))
        self.startsong_Eq.setObjectName("startsong_Eq")
        self.horizontalLayout_6.addWidget(self.startsong_Eq)

        self.stopm_Eq = QtWidgets.QPushButton(self.centralwidget)
        self.stopm_Eq.setTabletTracking(False)
        self.stopm_Eq.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopm_Eq.setIcon(icon9)
        self.stopm_Eq.setIconSize(QtCore.QSize(40, 40))
        self.stopm_Eq.setObjectName("stopm_Eq")
        self.horizontalLayout_6.addWidget(self.stopm_Eq)

        ############################## Fourier Eq #############

        spacerItem2 = QtWidgets.QSpacerItem(900, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.start_FourierEq = QtWidgets.QPushButton(self.centralwidget)
        self.start_FourierEq.setText("")
        self.start_FourierEq.setIcon(icon3)
        self.start_FourierEq.setIconSize(QtCore.QSize(40, 40))
        self.start_FourierEq.setObjectName("start_FourierEq")
        self.horizontalLayout_6.addWidget(self.start_FourierEq)
        
        self.delete_FourierEq = QtWidgets.QPushButton(self.centralwidget)
        self.delete_FourierEq.setText("")
        self.delete_FourierEq.setIcon(icon4)
        self.delete_FourierEq.setIconSize(QtCore.QSize(40, 40))
        self.delete_FourierEq.setObjectName("delete_FourierEq")
        self.horizontalLayout_6.addWidget(self.delete_FourierEq)
        
        ############################ Ham and save ############

        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        

        """ self.Ham = QtWidgets.QPushButton(self.centralwidget)
        self.Ham.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("ham2.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Ham.setIcon(icon10)
        self.Ham.setIconSize(QtCore.QSize(40, 40))
        self.Ham.setObjectName("Ham")
        self.horizontalLayout_6.addWidget(self.Ham) """

        """ self.save1 = QtWidgets.QPushButton(self.centralwidget)
        self.save1.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("save1.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save1.setIcon(icon10)
        self.save1.setIconSize(QtCore.QSize(40, 40))
        self.save1.setObjectName("Ham")
        self.horizontalLayout_6.addWidget(self.save1)

        self.save2 = QtWidgets.QPushButton(self.centralwidget)
        self.save2.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("save2.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save2.setIcon(icon10)
        self.save2.setIconSize(QtCore.QSize(40, 40))
        self.save2.setObjectName("save2")
        self.horizontalLayout_6.addWidget(self.save2) """

        #self.saved = QtWidgets.QPushButton(self.centralwidget)
        #self.saved.setText("")
        #icon10 = QtGui.QIcon()
        #icon10.addPixmap(QtGui.QPixmap("saved.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        #self.saved.setIcon(icon10)
        #self.saved.setIconSize(QtCore.QSize(40, 40))
        #self.saved.setObjectName("saved")
        #self.horizontalLayout_6.addWidget(self.saved)

        

        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")

########################## Plot Eq  #############################

        self.winEq = PlotWidget(self.centralwidget)
        self.winEq.setObjectName("winEq")
        self.gridLayout_2.addWidget(self.winEq, 0, 0, 1, 1)
        
        self.winEq_FF = PlotWidget(self.centralwidget)
        self.winEq_FF.setObjectName("winEq_FF")
        self.gridLayout_2.addWidget(self.winEq_FF, 0, 1, 1, 1)

############################## Fonts And sliders labels  ###########     
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.eqlabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.eqlabel.setFont(font)
        self.eqlabel.setObjectName("eqlabel")
        self.verticalLayout_2.addWidget(self.eqlabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(55, -1, 11, -1)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.freq1 = QtWidgets.QLabel(self.centralwidget)
        self.freq1.setObjectName("freq1")
        self.horizontalLayout_4.addWidget(self.freq1)
        self.freq2 = QtWidgets.QLabel(self.centralwidget)
        self.freq2.setObjectName("freq2")
        self.horizontalLayout_4.addWidget(self.freq2)
        self.freq3 = QtWidgets.QLabel(self.centralwidget)
        self.freq3.setObjectName("freq3")
        self.horizontalLayout_4.addWidget(self.freq3)
        self.freq4 = QtWidgets.QLabel(self.centralwidget)
        self.freq4.setObjectName("freq4")
        self.horizontalLayout_4.addWidget(self.freq4)
        self.freq5 = QtWidgets.QLabel(self.centralwidget)
        self.freq5.setObjectName("freq5")
        self.horizontalLayout_4.addWidget(self.freq5)
        self.freq6 = QtWidgets.QLabel(self.centralwidget)
        self.freq6.setObjectName("freq6")
        self.horizontalLayout_4.addWidget(self.freq6)
        self.freq7 = QtWidgets.QLabel(self.centralwidget)
        self.freq7.setObjectName("freq7")
        self.horizontalLayout_4.addWidget(self.freq7)
        self.freq8 = QtWidgets.QLabel(self.centralwidget)
        self.freq8.setObjectName("freq8")
        self.horizontalLayout_4.addWidget(self.freq8)
        self.freq9 = QtWidgets.QLabel(self.centralwidget)
        self.freq9.setObjectName("freq9")
        self.horizontalLayout_4.addWidget(self.freq9)
        self.freq10 = QtWidgets.QLabel(self.centralwidget)
        self.freq10.setObjectName("freq10")
        self.horizontalLayout_4.addWidget(self.freq10)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
 
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 162, 162))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 162, 162))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 162, 162))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        
        ###################### Sliders ###########################

        self.slider1 = QtWidgets.QSlider(self.centralwidget)
        self.slider1.setPalette(palette)
        self.slider1.setMinimum(0.1)
        self.slider1.setMaximum(10)
        self.slider1.setSliderPosition(0)
        self.slider1.setOrientation(QtCore.Qt.Vertical)
        self.slider1.setObjectName("slider1")
        self.horizontalLayout_2.addWidget(self.slider1)
        
        self.slider2 = QtWidgets.QSlider(self.centralwidget)
        self.slider2.setMinimum(0.1)
        self.slider2.setMaximum(10)
        self.slider2.setSliderPosition(0)
        self.slider2.setOrientation(QtCore.Qt.Vertical)
        self.slider2.setObjectName("slider2")
        self.horizontalLayout_2.addWidget(self.slider2)
        
        self.slider3 = QtWidgets.QSlider(self.centralwidget)
        self.slider3.setMinimum(0.1)
        self.slider3.setMaximum(10)
        self.slider3.setSliderPosition(0)
        self.slider3.setOrientation(QtCore.Qt.Vertical)
        self.slider3.setObjectName("slider3")
        self.horizontalLayout_2.addWidget(self.slider3)
        
        self.slider4 = QtWidgets.QSlider(self.centralwidget)
        self.slider4.setMinimum(0.1)
        self.slider4.setMaximum(10)
        self.slider4.setSliderPosition(0)
        self.slider4.setOrientation(QtCore.Qt.Vertical)
        self.slider4.setObjectName("slider4")
        self.horizontalLayout_2.addWidget(self.slider4)
        
        self.slider5 = QtWidgets.QSlider(self.centralwidget)
        self.slider5.setMinimum(0.1)
        self.slider5.setMaximum(10)
        self.slider5.setSliderPosition(0)
        self.slider5.setOrientation(QtCore.Qt.Vertical)
        self.slider5.setObjectName("slider5")
        self.horizontalLayout_2.addWidget(self.slider5)
        
        self.slider6 = QtWidgets.QSlider(self.centralwidget)
        self.slider6.setMinimum(0.1)
        self.slider6.setMaximum(10)
        self.slider6.setSliderPosition(0)
        self.slider6.setOrientation(QtCore.Qt.Vertical)
        self.slider6.setObjectName("slider6")
        self.horizontalLayout_2.addWidget(self.slider6)
        
        self.slider7 = QtWidgets.QSlider(self.centralwidget)
        self.slider7.setMinimum(0.1)
        self.slider7.setMaximum(10)
        self.slider7.setSliderPosition(0)
        self.slider7.setOrientation(QtCore.Qt.Vertical)
        self.slider7.setObjectName("slider7")
        self.horizontalLayout_2.addWidget(self.slider7)
        
        self.slider8 = QtWidgets.QSlider(self.centralwidget)
        self.slider8.setMinimum(0.1)
        self.slider8.setMaximum(10)
        self.slider8.setSliderPosition(0)
        self.slider8.setOrientation(QtCore.Qt.Vertical)
        self.slider8.setObjectName("slider8")
        self.horizontalLayout_2.addWidget(self.slider8)
        
        self.slider9 = QtWidgets.QSlider(self.centralwidget)
        self.slider9.setMinimum(0.1)
        self.slider9.setMaximum(10)
        self.slider9.setSliderPosition(0)
        self.slider9.setOrientation(QtCore.Qt.Vertical)
        self.slider9.setTickInterval(0)
        self.slider9.setObjectName("slider9")
        self.horizontalLayout_2.addWidget(self.slider9)
        
        self.slider10 = QtWidgets.QSlider(self.centralwidget)
        self.slider10.setMinimum(0.1)
        self.slider10.setMaximum(10)
        self.slider10.setSliderPosition(0)
        self.slider10.setOrientation(QtCore.Qt.Vertical)
        self.slider10.setObjectName("slider10")
        self.horizontalLayout_2.addWidget(self.slider10)
        
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(60, -1, 1, -1)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gain1 = QtWidgets.QLabel(self.centralwidget)
        self.gain1.setObjectName("gain1")
        self.horizontalLayout_3.addWidget(self.gain1)
        self.gain2 = QtWidgets.QLabel(self.centralwidget)
        self.gain2.setObjectName("gain2")
        self.horizontalLayout_3.addWidget(self.gain2)
        self.gain3 = QtWidgets.QLabel(self.centralwidget)
        self.gain3.setObjectName("gain3")
        self.horizontalLayout_3.addWidget(self.gain3)
        self.gain4 = QtWidgets.QLabel(self.centralwidget)
        self.gain4.setObjectName("gain4")
        self.horizontalLayout_3.addWidget(self.gain4)
        self.gain5 = QtWidgets.QLabel(self.centralwidget)
        self.gain5.setObjectName("gain5")
        self.horizontalLayout_3.addWidget(self.gain5)
        self.gain6 = QtWidgets.QLabel(self.centralwidget)
        self.gain6.setObjectName("gain6")
        self.horizontalLayout_3.addWidget(self.gain6)
        self.gain7 = QtWidgets.QLabel(self.centralwidget)
        self.gain7.setObjectName("gain7")
        self.horizontalLayout_3.addWidget(self.gain7)
        self.gain8 = QtWidgets.QLabel(self.centralwidget)
        self.gain8.setObjectName("gain8")
        self.horizontalLayout_3.addWidget(self.gain8)
        self.gain9 = QtWidgets.QLabel(self.centralwidget)
        self.gain9.setObjectName("gain9")
        self.horizontalLayout_3.addWidget(self.gain9)
        self.gain10 = QtWidgets.QLabel(self.centralwidget)
        self.gain10.setObjectName("gain10")
        self.horizontalLayout_3.addWidget(self.gain10)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 26))
        self.menubar.setObjectName("menubar")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.menuWindow_Function = QtWidgets.QMenu(self.menubar)
        self.menuWindow_Function.setObjectName("menuWindow_Function")
        self.menuSave_Results = QtWidgets.QMenu(self.menubar)
        self.menuSave_Results.setObjectName("menuSave_Results")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        #self.actionSave_as.setObjectName("actionSave_as")
        self.actionShowResults = QtWidgets.QAction(MainWindow)
        self.actionShowResults.setObjectName("actionShowResults")
        self.actionRectangular_Window = QtWidgets.QAction(MainWindow)
        self.actionRectangular_Window.setObjectName("actionRectangular_Window")
        self.actionHann_Window = QtWidgets.QAction(MainWindow)
        self.actionHann_Window.setObjectName("actionHann_Window")
        self.actionHamming_Window = QtWidgets.QAction(MainWindow)
        self.actionHamming_Window.setObjectName("actionHamming_Window")
        self.actionOutputOne = QtWidgets.QAction(MainWindow)
        self.actionOutputOne.setObjectName("actionOutputOne")
        self.actionOutputTwo = QtWidgets.QAction(MainWindow)
        self.actionOutputTwo.setObjectName("actionOutputTwo")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.menuData.addAction(self.actionOpen)
        self.menuData.addAction(self.actionSave)
        self.menuData.addAction(self.actionShowResults)
        self.menuData.addSeparator()
        self.menuData.addAction(self.actionExit_2)
        self.menuWindow_Function.addAction(self.actionRectangular_Window)
        self.menuWindow_Function.addAction(self.actionHann_Window)
        self.menuWindow_Function.addAction(self.actionHamming_Window)
        self.menuSave_Results.addAction(self.actionOutputOne)
        self.menuSave_Results.addAction(self.actionOutputTwo)
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuWindow_Function.menuAction())
        self.menubar.addAction(self.menuSave_Results.menuAction())

        self.retranslateUi(MainWindow)
        self.slider1.sliderMoved['int'].connect(self.gain1.setNum)
        self.slider2.sliderMoved['int'].connect(self.gain2.setNum)
        self.slider3.sliderMoved['int'].connect(self.gain3.setNum)
        self.slider4.sliderMoved['int'].connect(self.gain4.setNum)
        self.slider5.sliderMoved['int'].connect(self.gain5.setNum)
        self.slider6.sliderMoved['int'].connect(self.gain6.setNum)
        self.slider7.sliderMoved['int'].connect(self.gain7.setNum)
        self.slider8.sliderMoved['int'].connect(self.gain8.setNum)
        self.slider9.sliderMoved['int'].connect(self.gain9.setNum)
        self.slider10.sliderMoved['int'].connect(self.gain10.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Graphic Equalizer Studio"))
        
        self.startbutton1.setToolTip(_translate("MainWindow", "Pause"))
        self.pausebutton1.setToolTip(_translate("MainWindow", "Stop"))
        self.startsong_orig.setToolTip(_translate("MainWindow", "Start_Song"))
        self.stopm_orig.setToolTip(_translate("MainWindow", "Stop_song"))
        
        self.startbuttonEq.setToolTip(_translate("MainWindow", "Pause"))
        self.pausebuttonEq.setToolTip(_translate("MainWindow", "Stop"))
        self.startsong_Eq.setToolTip(_translate("MainWindow", "Start_Song"))
        self.stopm_Eq.setToolTip(_translate("MainWindow", "Stop_song"))

        self.startbuttonFForig.setToolTip(_translate("MainWindow", "draw"))
        self.stopbuttonFForig.setToolTip(_translate("MainWindow", "delete"))
        
        
        self.eqlabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">   EQ SETUP FLAT</p></body></html>"))
        self.freq1.setText(_translate("MainWindow","(0.0045:1274.3)"))
        self.freq2.setText(_translate("MainWindow", "(1274.3:2548.6)"))
        self.freq3.setText(_translate("MainWindow", "(2548.6:3822.9)"))
        self.freq4.setText(_translate("MainWindow", "(3822.9:5097.2)"))
        self.freq5.setText(_translate("MainWindow", "(5097.2:6371.5)"))
        self.freq6.setText(_translate("MainWindow", "(6371.5:7645.8)"))
        self.freq7.setText(_translate("MainWindow", "(7645.8:8920.1)"))
        self.freq8.setText(_translate("MainWindow", "(8920.1:10194.4)"))
        self.freq9.setText(_translate("MainWindow", "(10194.4:11468.7)"))
        self.freq10.setText(_translate("MainWindow", "(11468.7:12743)   Hz"))
        self.gain1.setText(_translate("MainWindow", "0"))
        self.gain2.setText(_translate("MainWindow", "0"))
        self.gain3.setText(_translate("MainWindow", "0"))
        self.gain4.setText(_translate("MainWindow", "0"))
        self.gain5.setText(_translate("MainWindow", "0"))
        self.gain6.setText(_translate("MainWindow", "0"))
        self.gain7.setText(_translate("MainWindow", "0"))
        self.gain8.setText(_translate("MainWindow", "0"))
        self.gain9.setText(_translate("MainWindow", " 0  "))
        self.gain10.setText(_translate("MainWindow", "0"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.menuWindow_Function.setTitle(_translate("MainWindow", "Window Function"))
        self.menuSave_Results.setTitle(_translate("MainWindow", "Save Outputs"))
        self.actionOpen.setText(_translate("MainWindow", "Load Project File"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save Project File"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionShowResults.setText(_translate("MainWindow", "Show Results"))
        self.actionRectangular_Window.setText(_translate("MainWindow", "Rectangular Window"))
        self.actionHann_Window.setText(_translate("MainWindow", "Hann Window"))
        self.actionHamming_Window.setText(_translate("MainWindow", "Hamming Window"))
        self.actionOutputOne.setText(_translate("MainWindow", "Output One"))
        self.actionOutputTwo.setText(_translate("MainWindow", "Output Two"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
